language: php
php:
- 7.0

script:
# Override default Travis script action [phpunit]
- php -l *.php

branches:
  only:
  - master

# Enable Travis deployment
deploy:
  # Use script as a deployment tool
  provider: script
  script: ./deploy/deploy.sh